### PR TITLE
Test development

### PR DESCRIPTION
**Pull request by mikenguyen01**
Added 3 tests (basic operation: initialization, disposal and adding new entries).
Test ran successfully.

### CODE REVIEW

**Review by bincity2003 — COMMENTED** [review]
Can't approve it yet. Still missing test cases covering other parts of the DbTable library. It's still a good leap, though. Keep working!

**Comment by bincity2003** [comment]
Also, this PR resolve #2 and #3

**Comment by mikenguyen01** [comment]
I added 4 more test to cover most of the functionality. Please review my work, thanks!

**Review by bincity2003 — DISMISSED** [review]
It looks like you’ve covered everything, except Execute (future improvement), right? I think it’s enough tests, for now! We will have to add more later. Approved!

**Review by bincity2003 — APPROVED** [review]
Just a small fix in README file. Still approved!

**Pull request merged**
